version: '3.0'

services:
  grafana:
    privileged: true
    container_name: 'sdague-ibmlogs-datasource'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-11.6.0}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/sdague-ibmlogs-datasource
      - ./provisioning:/etc/grafana/provisioning
