version: '3.0'

services:
  grafana:
    privileged: true
    container_name: 'sdague-mezmo-datasource'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-11.2.0}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/sdague-mezmo-datasource
      - ./provisioning:/etc/grafana/provisioning
