version: '3.0'

services:
  grafana:
    container_name: 'ibmqsoftware-logdna-datasource'
    privileged: true
    # user: 1000:1000
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-9.5.1}
    #network_mode: host
    ports:
       - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/ibmqsoftware-logdna-datasource
      - ./provisioning:/etc/grafana/provisioning
